name: Content Ex Machina
favicon: null
layout_spectrum: 0.32939713122323155
typography_spectrum: 0.22340919612906873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.35187346767634153
  lightness: 0.740338139468804
  saturation: 0.0737885890994221
  rhythmicContrast: 0.31975488807074726
purpose: []
